name : First workflow

# Trigger

on:
  workflow_dispatch:
  push:

jobs: 
    Hello-Job:
      runs-on : ubuntu-latest
      steps:
        - name : Hello World
          run : echo "Hello World"
          
  
